opt_in_rules:
- attributes
- closure_end_indentation
- closure_spacing
- contains_over_first_not_nil
- empty_count
- empty_string
- explicit_init
- fatal_error_message
- file_header
- first_where
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- no_extension_access_modifier
- operator_usage_whitespace
- overridden_super_call
- redundant_nil_coalescing
- redundant_type_annotation
- sorted_first_last
- switch_case_on_newline
- unneeded_parentheses_in_closure_argument
- unused_import
- yoda_condition

disabled_rules:
- cyclomatic_complexity
- empty_parentheses_with_trailing_closure
- trailing_whitespace
- private_over_fileprivate
- force_cast
- force_try

attributes:
  always_on_same_line:
  - '@objc'
  - '@IBAction'

line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_function_declarations: true

file_length:
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 400

vertical_whitespace:
  max_empty_lines: 2

large_tuple:
  warning: 4

identifier_name:
  excluded:
  - id
  - vc

file_header:
  required_pattern: ''

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true

custom_rules:
  single_line_return:
    included: ".*.swift"
    regex: '\.\S+ *\{(?: *return|[^\n\}]+ in return) [^\}]+\}'
    name: "Single Line Return"
    message: "Remove the 'return' when returning from a single line closure."
    severity: warning
  vertical_whitespace_closing_braces:
    included: ".*.swift"
    regex: '(?<=\n)[ \t]*\n[ \t]*[)}\]]'
    name: "Vertical Whitespace before Closing Braces"
    message: "Don't include vertical whitespace (empty line) before closing braces."
    severity: warning
  comments_space:
    name: "Space After Comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning
  empty_line_after_guard:
    name: "Empty Line After Guard"
    regex: '(^ *guard[ a-zA-Z0-9=?.\(\),><!]*\{[ a-zA-Z0-9=?.\(\),><!]*\}\n *(?!(?:return|guard))\S+)'
    message: "There should be an empty line after a guard"
    severity: warning
  empty_line_after_super:
    name: "Empty Line After Super"
    regex: '(^ *super\.[ a-zA-Z0-9=?.\(\)\{\}:,><!]*\n *(?!(?:\}|return))\S+)'
    message: "There should be an empty line after super"
    severity: warning
  double_space:
    include: "*.swift"
    name: "Double space"
    regex: '([a-z,A-Z] \s+)'
    message: "Don't use double space between keywords"
    match_kinds: keyword
    severity: warning
  empty_commented_line:
    name: "Empty Commented Out Line"
    regex: '(\t+| +)//\n'
    message: "Remove useless comment lines or use /* format */"
    severity: warning
  missing_closure_name:
    name: "Missing closure name"
    regex: '^\s*\}\) \{.*'
    message: "Add the missing closure name"
    severity: warning

excluded:
- Pods
- fastlane
- CaronaeUITests/SnapshotHelper.swift
