version: 2

references:
  defaults: &defaults
    working_directory: /Users/distiller/project
    macos:
      xcode: "9.3.0"
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output
    shell: /bin/bash --login -o pipefail

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v2-repo-{{ .Branch }}-{{ .Revision }}
        - v2-repo-{{ .Branch }}
        - v2-repo

jobs:
  configure-code:
    <<: *defaults
    steps:
      - *restore_repo
      - run:
          name: Configure Git
          command: |
            git config --global user.email "circleci@caronae.org"
            git config --global user.name "CircleCI"
      - checkout
      - run: bundle install --path vendor/bundle
      - run:
          name: Fetch CocoaPods specs
          command: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Prepare build
          command: bundle exec fastlane prepare_build
      - run:
          name: Persist build number
          command: echo ${CIRCLE_BUILD_NUM} > build_number.txt
      - save_cache:
          key: v2-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  build-prod:
    <<: *defaults
    steps:
      - *restore_repo
      - run:
          name: Build app
          command: bundle exec fastlane build
      - store_artifacts:
          path: output/buildlogs
      - persist_to_workspace:
          root: output
          paths:
            - gym/Caronae.ipa
            - gym/Caronae.app.dSYM.zip

  build-dev:
    <<: *defaults
    steps:
      - *restore_repo
      - run:
          name: Build app
          command: bundle exec fastlane build --env dev
      - store_artifacts:
          path: output/buildlogs
      - persist_to_workspace:
          root: output
          paths:
            - gym/Caronae.ipa
            - gym/Caronae.app.dSYM.zip

  deploy-testflight-prod:
    <<: *defaults
    steps:
      - *restore_repo
      - attach_workspace:
          at: output
      - run:
          name: Publish app to TestFlight
          command: bundle exec fastlane beta ipa:output/gym/Caronae.ipa

  deploy-testflight-dev:
    <<: *defaults
    steps:
      - *restore_repo
      - attach_workspace:
          at: output
      - run:
          name: Publish app to TestFlight
          command: bundle exec fastlane beta ipa:output/gym/Caronae.ipa --env dev

  deploy-appstore-prod:
    <<: *defaults
    steps:
      - *restore_repo
      - attach_workspace:
          at: output
      - run: brew install imagemagick
      - run: brew install graphicsmagick
      - run:
          name: Publish app to App Store
          command: bundle exec fastlane deploy build_number:"$(cat build_number.txt)"

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - configure-code:
          filters:
            branches:
              only: master
      - build-prod:
          requires:
            - configure-code
      - build-dev:
          requires:
            - configure-code
      - deploy-testflight-prod:
          requires:
            - build-prod
      - deploy-testflight-dev:
          requires:
            - build-dev
      - hold-prod:
          type: approval
          requires:
           - deploy-testflight-prod
      - deploy-appstore-prod:
          requires:
           - hold-prod
